### ISSUE TITLE
Memory not shown in greeting

### ISSUE THREAD

**Issue by Fredmf** [oh-my-fish/theme-fishbone#7] opened 2018-08-31 06:30 UTC
https://github.com/oh-my-fish/theme-fishbone/blob/11e77c9853f99e647f2b7bde0607eb52a229b188/fish_greeting.fish#L103

-f 12 does not work on my system, iam using fedora 28, cut -f 13 gives the right value

**Comment by pantuza** [comment] 2018-09-11 14:57
Hi, @Fredmf .

I could not reproduce the error. I've tried it on a docker container running fedora 28 with the following commands:

```bash
$> docker run -it --rm --name fedora fedora:latest bash
$> cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
$> yum update -y && yum install procps    # Installs free command
$> free -h | grep "Mem" | cut -d " " -f 12
2.0G
```

As a follow up, check if your *procps* installation is in the latest version:

```bash
$> free --version
free from procps-ng 3.3.12
```

Regards.

**Comment by yunusozd** [comment] 2020-05-10 21:04
Hello there, long time ago someone issued this but still I have the same problem. In fact, I tried 
`free -h | grep "Mem" | cut -d " " -f 12` command but nothing showed but I tried without `cut -d " " -f 12` and It showed `Mem:          7,7Gi       2,1Gi       4,0Gi       138Mi       1,5Gi       5,2Gi`. What is your opinion? I use Fedora 32.

**Comment by pantuza** [comment] 2020-06-03 21:37
Hi, @yunusozd . Sorry for the delay. And thanks for reaching out. 

I think I have to update this code to use `cut -d " " -f 11`. Can you try with `-f 11` in order to us to check if that works?

**Comment by pantuza** [comment] 2020-06-03 21:45
Actually, I could reproduce the error. This is fixed on the master branch.
Please update the theme using `omf` as follows:

```bash
$> omf update fishbone
```

or if you uninstalled it, just reinstall to get latest version. To test if the Memory information is being shown just call `fish_greeting` on your terminal. 

Once again, thanks a lot for reaching out and sorry for the delay. 

--
Happy Hacking with Oh My Fish!

**Closed as completed** 2020-06-03 21:46 UTC
Labels: bug
